export const FETCH_COMMENTIDS_REQUEST = 'FETCH_COMMENTIDS_REQUEST'
export const FETCH_COMMENTIDS_SUCCESS = 'FETCH_COMMENTIDS_SUCCESS'
export const FETCH_COMMENTIDS_FAILURE = 'FETCH_COMMENTIDS_FAILURE'